'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { getTranslations, getNestedValue } from '@/lib/translations';

interface LanguageContextType {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string, params?: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<'en' | 'ar'>('en');

  // Load language from localStorage on mount and apply RTL immediately
  useEffect(() => {
    const savedLanguage = localStorage.getItem('clutch-language') as 'en' | 'ar';
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
      // Apply RTL immediately on mount
      if (savedLanguage === 'ar') {
        document.documentElement.dir = 'rtl';
        document.documentElement.lang = 'ar';
      } else {
        document.documentElement.dir = 'ltr';
        document.documentElement.lang = 'en';
      }
    }
  }, []);

  // Apply RTL direction whenever language changes
  useEffect(() => {
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = 'en';
    }
  }, [language]);

  // Save language to localStorage when it changes
  const setLanguage = (lang: 'en' | 'ar') => {
    setLanguageState(lang);
    localStorage.setItem('clutch-language', lang);
  };

  // Translation function with fallback
  const t = (key: string, params?: any) => {
    try {
      // Load translations using the reliable loader
      const translations = getTranslations(language);

    // Fallback translations if loading fails
    const fallbackTranslations: Record<string, string> = {
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.add': 'Add',
      'common.search': 'Search...',
      'common.filter': 'Filter',
      'common.export': 'Export',
      'common.import': 'Import',
      'common.refresh': 'Refresh',
      'common.close': 'Close',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.previous': 'Previous',
      'common.submit': 'Submit',
      'common.reset': 'Reset',
      'common.confirm': 'Confirm',
      'common.yes': 'Yes',
      'common.no': 'No',
      'navigation.dashboard': 'Dashboard',
      'navigation.userManagement': 'User Management',
      'navigation.fleetManagement': 'Fleet Management',
      'navigation.crm': 'CRM',
      'navigation.chat': 'Chat',
      'navigation.aiDashboard': 'AI Dashboard',
      'navigation.enterprise': 'Enterprise',
      'navigation.finance': 'Finance',
      'navigation.legal': 'Legal',
      'navigation.hr': 'HR',
      'navigation.featureFlags': 'Feature Flags',
      'navigation.communication': 'Communication',
      'navigation.analytics': 'Analytics',
      'navigation.mobileApps': 'Mobile Apps',
      'navigation.cms': 'CMS',
      'navigation.marketing': 'Marketing',
      'navigation.projects': 'Projects',
      'navigation.settings': 'Settings',
      'navigation.reports': 'Reports',
      'navigation.integrations': 'Integrations',
      'navigation.auditTrail': 'Audit Trail',
      'navigation.apiDocs': 'API Docs',
      'navigation.assets': 'Assets',
      'navigation.vendors': 'Vendors',
        'navigation.systemHealth': 'System Health',
        // Sidebar translations
        'sidebar.collapse': 'Collapse',
        // Theme translations
        'theme.toggle': 'Toggle theme',
        'theme.light': 'Light',
        'theme.dark': 'Dark',
        'theme.system': 'System',
        // Header translations
        'header.search': 'Search...',
        'header.notifications': 'Notifications',
        'header.myAccount': 'My Account',
        'header.profile': 'Profile',
        'header.settings': 'Settings',
        'header.language': 'Language',
        // Common translations
        'search': 'Search...',
        'conversionRate': 'Conversion Rate',
        'operationsTrendingPositive': 'Operations trending positive',
        'excellent': 'Excellent',
        'fleetOperations': 'Fleet Operations',
        'infrastructure': 'Infrastructure',
        'maintenance': 'Maintenance',
        'other': 'Other',
        'ofTotalCosts': 'of total costs',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'none': 'None',
        'overallComplianceStatus': 'Overall Compliance Status',
        'pendingApprovals': 'Pending Approvals',
        'violations': 'Violations',
        'securityIncidents': 'Security Incidents',
        'complianceBreakdown': 'Compliance Breakdown',
        'awaitingReview': 'Awaiting Review',
        'complianceViolations': 'Compliance Violations',
        'policyBreaches': 'Policy Breaches',
        'securityBreaches': 'Security Breaches',
        'auditTimeline': 'Audit Timeline',
        'lastAudit': 'Last Audit',
        'completedSuccessfully': 'Completed successfully',
        'passed': 'Passed',
        'nextAudit': 'Next Audit',
        'scheduledAudit': 'Scheduled audit',
        'complianceProgress': 'Compliance Progress',
        'overallCompliance': 'Overall Compliance',
        'exportReport': 'Export Report',
        'complianceInsights': 'Compliance Insights',
        'someAreasNeedAttention': 'Some areas need attention - review pending approvals',
        'nextAuditIn': 'Next audit in {days} days',
        'approvalsPendingReview': '{count} approvals pending review',
        'violationsNeedResolution': '{count} compliance violations need resolution',
        'top5EnterpriseClients': 'Top 5 Enterprise Clients',
        'byRevenueContribution': 'By revenue contribution & activity level',
        'totalRevenue': 'Total Revenue',
        'avgGrowth': 'Avg Growth',
        'revenueDistribution': 'Revenue Distribution',
        'growthAnalysis': 'Growth Analysis',
        'growingClients': 'Growing Clients',
        'decliningClients': 'Declining Clients',
        'viewAllClients': 'View All Clients',
        'scheduleReview': 'Schedule Review',
        'clientInsights': 'Client Insights',
        'topClientContributes': 'Top client contributes {percentage}% of total revenue',
        'clientsShowingGrowth': '{growing} out of {total} clients showing positive growth',
        'averageClientActivity': 'Average client activity level: {percentage}%',
        'totalEnterpriseRevenue': 'Total enterprise revenue: {amount} EGP',
        // User management widget translations
        'widgets.userGrowthCohort': 'User Growth Cohort',
        'widgets.engagementHeatmap': 'Engagement Heatmap',
        'widgets.onboardingCompletion': 'Onboarding Completion',
        'widgets.roleDistribution': 'Role Distribution',
        'widgets.retained': 'Retained',
        'widgets.retentionRate': 'Retention Rate',
        'widgets.cohortAnalysis': 'Cohort Analysis',
        'widgets.tracksNewSignups': 'Tracks new signups vs retained users per month',
        'widgets.loadingCohortAnalysis': 'Loading cohort analysis...',
        'widgets.noCohortData': 'No cohort data available',
        'widgets.loadingHeatmapData': 'Loading engagement heatmap...',
        'widgets.noHeatmapData': 'No engagement data available',
        'widgets.loadingRoleData': 'Loading role distribution...',
        'widgets.noRoleData': 'No role data available',
        'widgets.loadingOnboardingData': 'Loading onboarding completion...',
        'widgets.noOnboardingData': 'No onboarding data available',
        // User management page translations
        'users.searchUsers': 'Search users...',
        'users.unknownUser': 'Unknown User',
        'users.noEmail': 'No email',
        'users.never': 'Never',
        'users.unknown': 'Unknown',
        'users.unknownError': 'Unknown error occurred',
        'users.failedToLoadUsers': 'Failed to load users: {error}',
        'users.headAdministrator': 'Head Administrator',
        'users.platformAdmin': 'Platform Admin',
        'users.administrator': 'Administrator',
        'users.manager': 'Manager',
        'users.hrManager': 'HR Manager',
        'users.financeManager': 'Finance Manager',
        'users.operationsManager': 'Operations Manager',
        'users.marketingManager': 'Marketing Manager',
        'users.legalManager': 'Legal Manager',
        'users.securityManager': 'Security Manager',
        'users.businessAnalyst': 'Business Analyst',
        'users.projectManager': 'Project Manager',
        'users.assetManager': 'Asset Manager',
        'users.crmManager': 'CRM Manager',
        'users.systemAdmin': 'System Admin',
        'users.hrSpecialist': 'HR Specialist',
        'users.financeSpecialist': 'Finance Specialist',
        'users.customerSupport': 'Customer Support',
        'users.developer': 'Developer',
        'users.employee': 'Employee',
        'users.support': 'Support',
        'users.enterpriseClient': 'Enterprise Client',
        'users.serviceProvider': 'Service Provider',
        'users.userAccess': 'User access',
        'users.fillAllFields': 'Please fill in all required fields',
        'users.userCreatedSuccessfully': 'User created successfully',
        'users.failedToCreateUser': 'Failed to create user: {error}',
        'users.createNewUser': 'Create New User',
        'users.userDetails': 'User Details',
        'users.enterUserName': 'Enter user name',
        'users.enterEmail': 'Enter email address',
        'users.selectRole': 'Select role',
        'users.selectStatus': 'Select status',
        'users.cancel': 'Cancel',
        'users.create': 'Create',
        'users.name': 'Name',
        'users.email': 'Email',
        'users.role': 'Role',
        'users.status': 'Status',
        'users.active': 'Active',
        'users.inactive': 'Inactive',
        'users.pending': 'Pending',
        // Widget specific translations
        'widgets.retained': 'Retained',
        'widgets.averageRetention': 'Average Retention',
        'widgets.monthlyCohorts': 'Monthly Cohorts',
        'widgets.cohort': 'Cohort',
        'widgets.retentionTrend': 'Retention Trend',
        'widgets.highRetention': 'High Retention',
        'widgets.lowRetention': 'Low Retention',
        'widgets.cohortInsights': 'Cohort Insights',
        'widgets.averageRetentionRate': 'Average retention rate: {rate}%',
        'widgets.cohortsWithHighRetention': '{count} cohorts with high retention (80%+)',
        'widgets.totalNewUsersInPeriod': 'Total new users in period: {count}',
        'widgets.totalRetainedUsers': 'Total retained users: {count}',
        'widgets.retentionBelowTarget': 'Retention below target - consider onboarding improvements',
        'widgets.engagementHeatmap': 'Engagement Heatmap',
        'widgets.showsFeatureUsage': 'Shows feature usage by user segment',
        'widgets.allSegments': 'All Segments',
        'widgets.averageUsage': 'Average Usage',
        'widgets.segments': 'Segments',
        'widgets.featureUsageHeatmap': 'Feature Usage Heatmap',
        'widgets.topPerformingFeatures': 'Top Performing Features',
        'widgets.usageDistribution': 'Usage Distribution',
        'widgets.high': 'High (80%+)',
        'widgets.medium': 'Medium (60-79%)',
        'widgets.low': 'Low (40-59%)',
        'widgets.veryLow': 'Very Low (<40%)',
        'widgets.engagementInsights': 'Engagement Insights',
        'widgets.averageFeatureUsage': 'Average feature usage: {rate}%',
        'widgets.topFeature': 'Top feature: {feature} ({rate}% usage)',
        'widgets.featuresWithHighEngagement': '{count} features with high engagement (80%+)',
        'widgets.featuresNeedAttention': '{count} features need attention (<40% usage)',
        'widgets.onboardingCompletion': 'Onboarding Completion',
        'widgets.unableToLoadOnboardingData': 'Unable to load onboarding data',
        'widgets.roleDistribution': 'Role Distribution',
        'widgets.pieChartOfRoles': 'Pie chart of admins, managers, staff, etc.',
        'widgets.totalUsers': 'Total Users',
        'widgets.roles': 'Roles',
        'widgets.largestRole': 'Largest Role',
        'widgets.roleBreakdown': 'Role Breakdown',
        'widgets.distribution': 'Distribution',
        'widgets.smallestRole': 'Smallest Role',
        'widgets.roleInsights': 'Role Insights',
        'widgets.totalUsersInSystem': 'Total users: {count}',
        'widgets.differentRolesInSystem': '{count} different roles in the system',
        'widgets.largestRolePercentage': 'Largest role: {role} ({percentage}%)',
        'widgets.smallestRolePercentage': 'Smallest role: {role} ({percentage}%)',
        'widgets.excellent': 'Excellent',
        'widgets.good': 'Good',
        'widgets.fair': 'Fair',
        'widgets.poor': 'Poor',
        // Role descriptions
        'roles.fullSystemAccess': 'Full system access and control',
        'roles.systemAdministration': 'System administration and management',
        'roles.executiveLeadership': 'Executive leadership and oversight',
        'roles.platformAdministration': 'Platform administration and control',
        'roles.administrativeAccess': 'Administrative access and management',
        'roles.humanResourcesManagement': 'Human resources management',
        'roles.financialManagement': 'Financial management and oversight',
        'roles.operationsManagement': 'Operations and fleet management',
        'roles.marketingManagement': 'Marketing and customer acquisition',
        'roles.legalManagement': 'Legal and compliance management',
        'roles.securityManagement': 'Security and risk management',
        'roles.businessAnalysis': 'Business analysis and insights',
        'roles.projectManagement': 'Project management and coordination',
        'roles.assetManagement': 'Asset and fleet management',
        'roles.customerRelationshipManagement': 'Customer relationship management',
        'roles.systemMaintenance': 'System administration and maintenance',
        'roles.hrSpecialist': 'Human resources specialist',
        'roles.financeSpecialist': 'Financial operations specialist',
        'roles.customerSupportSpecialist': 'Customer support specialist',
        'roles.developmentSpecialist': 'Development and technical specialist',
        'roles.standardEmployeeAccess': 'Standard employee access',
        'roles.supportSpecialist': 'Support and assistance specialist',
        'roles.enterpriseClientAccess': 'Enterprise client access',
        'roles.serviceProviderAccess': 'Service provider access',
        // Additional widget translations
        'widgets.unableToLoadFinancialMetrics': 'Unable to load financial metrics',
        'widgets.sevenDays': '7 Days',
        'widgets.thirtyDays': '30 Days',
        'widgets.ninetyDays': '90 Days',
        'widgets.risk': 'Risk',
        'widgets.unableToLoadOperationalMetrics': 'Unable to load operational metrics',
        'widgets.dataStructureError': 'Data structure error - Check console for details',
        'widgets.complianceDataFormatError': 'The compliance data received does not match the expected format',
        'widgets.highUncertainty': 'High uncertainty - consider additional data sources',
        'widgets.topClientContributes': 'Top client contributes {percentage}% of total revenue',
        'widgets.clientsShowingGrowth': '{growing} out of {total} clients showing positive growth',
        'widgets.averageClientActivity': 'Average client activity level: {percentage}%',
        'widgets.totalEnterpriseRevenue': 'Total enterprise revenue: {amount} EGP',
        'users.fromLastMonth': 'from last month',
        'users.enterpriseClients': 'Enterprise Clients',
        'users.serviceProviders': 'Service Providers',
        'users.userAnalytics': 'User Analytics',
        'users.deepInsightsIntoUser': 'Deep insights into user behavior and engagement',
        'users.segments': 'Segments',
        'users.featureUsageHeatmap': 'Feature Usage Heatmap',
        'users.topPerformingFeatures': 'Top Performing Features',
        'users.usageDistribution': 'Usage Distribution',
        'users.unableToLoadOnboardingData': 'Unable to load onboarding data',
        'widgets.loadingOnboardingData': 'Loading onboarding data...',
        'widgets.onboardingCompletion': 'Onboarding Completion',
        'widgets.totalUsers': 'Total Users',
        'widgets.completed': 'Completed',
        'widgets.incomplete': 'Incomplete',
        'widgets.onboardingSteps': 'Onboarding Steps',
        'widgets.stepProgress': 'Step Progress',
        'widgets.bottlenecks': 'Bottlenecks',
        'widgets.topPerformingSteps': 'Top Performing Steps',
        'widgets.needsAttention': 'Needs attention',
        'widgets.performingWell': 'Performing well',
        'widgets.onboardingInsights': 'Onboarding Insights',
        'widgets.overallCompletionRate': 'Overall Completion Rate',
        'widgets.usersCompletedFullOnboarding': 'users completed full onboarding',
        'widgets.stepsNeedImprovement': 'steps need improvement',
        'widgets.stepsPerformingExcellent': 'steps performing excellently',
        'widgets.focusOn': 'Focus on:',
        'widgets.completion': 'completion',
        'widgets.percentageOfNewUsersCompletingOnboarding': '% of new users completing onboarding flows',
        'widgets.retained': 'Retained',
        'widgets.averageRetention': 'Average Retention',
        'widgets.monthlyCohorts': 'Monthly Cohorts',
        'widgets.retentionTrend': 'Retention Trend',
        'widgets.highRetention': 'High Retention',
        'widgets.lowRetention': 'Low Retention',
        'widgets.cohortInsights': 'Cohort Insights',
        'widgets.averageRetentionRate': 'Average retention rate: {rate}%',
        'widgets.cohortsWithHighRetention': '{count} cohorts with high retention (80%+)',
        'widgets.totalNewUsersInPeriod': 'Total new users in period: {count}',
        'widgets.totalRetainedUsers': 'Total retained users: {count}',
        'widgets.retentionBelowTarget': 'Retention below target - consider onboarding improvements',
        'widgets.engagementHeatmap': 'Engagement Heatmap',
        'widgets.showsFeatureUsage': 'Shows feature usage by user segment',
        'widgets.allSegments': 'All Segments',
        'widgets.averageUsage': 'Average Usage',
        'widgets.segments': 'Segments',
        'widgets.featureUsageHeatmap': 'Feature Usage Heatmap',
        'widgets.topPerformingFeatures': 'Top Performing Features',
        'widgets.usageDistribution': 'Usage Distribution',
        'widgets.high': 'High (80%+)',
        'widgets.medium': 'Medium (60-79%)',
        'widgets.low': 'Low (40-59%)',
        'widgets.veryLow': 'Very Low (<40%)',
        'widgets.engagementInsights': 'Engagement Insights',
        'widgets.averageFeatureUsage': 'Average feature usage: {rate}%',
        'widgets.topFeature': 'Top feature: {feature} ({rate}% usage)',
        'widgets.featuresWithHighEngagement': '{count} features with high engagement (80%+)',
        'widgets.featuresNeedAttention': '{count} features need attention (<40% usage)',
        'widgets.roleDistribution': 'Role Distribution',
        'widgets.pieChartOfRoles': 'Pie chart of admins, managers, staff, etc.',
        'widgets.totalUsers': 'Total Users',
        'widgets.roles': 'Roles',
        'widgets.largestRole': 'Largest Role',
        'widgets.roleBreakdown': 'Role Breakdown',
        'widgets.distribution': 'Distribution',
        'widgets.smallestRole': 'Smallest Role',
        'widgets.roleInsights': 'Role Insights',
        'widgets.totalUsersInSystem': 'Total users: {count}',
        'widgets.differentRolesInSystem': '{count} different roles in the system',
        'widgets.largestRolePercentage': 'Largest role: {role} ({percentage}%)',
        'widgets.smallestRolePercentage': 'Smallest role: {role} ({percentage}%)',
        'widgets.loadingRoleData': 'Loading role data...',
        'widgets.atRiskUsers': 'At Risk Users',
        'widgets.viewAll': 'View All',
        'widgets.riskPercentage': 'Risk %',
        'widgets.lastActive': 'Last Active',
        'widgets.weeksAgo': 'weeks ago',
        'widgets.factors': 'Factors',
        'widgets.predictedChurnTimeline': 'Predicted Churn Timeline',
        'widgets.confidence': 'confidence',
        'widgets.yesterday': 'Yesterday',
        'widgets.daysAgo': '{days} days ago',
        'widgets.weeksAgo': '{weeks} weeks ago',
        'widgets.monthsAgo': '{months} months ago',
        'widgets.viewAllUsers': 'View All Users',
        'widgets.loadingChurnRiskData': 'Loading churn risk data...',
        'widgets.vsLastMonth': 'vs last month',
        'widgets.ofTotalCosts': 'of total costs',
        'widgets.revenue': 'Revenue',
        'widgets.costs': 'Costs',
        'widgets.insights': 'Insights',
        'widgets.marginNeedsImprovement': 'Margin needs improvement - consider cost optimization',
        'widgets.fleetOperationsRepresent': 'Fleet operations represent {percentage}% of total costs',
        'widgets.infrastructureCostsStable': 'Infrastructure costs are stable at {amount} EGP/month',
        'widgets.atRiskUsers': 'At Risk Users',
        'widgets.viewAll': 'View All',
        'widgets.riskPercentage': 'Risk Percentage',
        'widgets.lastActive': 'Last Active',
        'widgets.factors': 'Factors',
        'widgets.predictedChurnTimeline': 'Predicted Churn Timeline',
        'widgets.sendRetentionCampaign': 'Send Retention Campaign',
        'widgets.viewAllUsers': 'View All Users',
        'widgets.revenueVsCosts': 'Revenue vs Costs',
        'widgets.monthlyRevenue': 'Monthly Revenue',
        'widgets.monthlyCosts': 'Monthly Costs',
        'widgets.needsAttention': 'Needs Attention',
        'widgets.netProfitMargin': 'Net Profit Margin',
        'widgets.costBreakdown': 'Cost Breakdown',
        'widgets.fleetOperations': 'Fleet Operations',
        'widgets.infrastructure': 'Infrastructure',
        'widgets.maintenance': 'Maintenance',
        'widgets.other': 'Other',
        'widgets.aiPoweredForecast': 'AI-Powered Forecast',
        'widgets.nextPeriodRevenueProjection': 'Next Period Revenue Projection',
        'widgets.projectedRevenue': 'Projected Revenue',
        'widgets.baseCase': 'Base Case',
        'widgets.avgConfidence': 'Avg Confidence',
        'widgets.lowRisk': 'Low Risk',
        'widgets.scenarioAnalysis': 'Scenario Analysis',
        'widgets.optimistic': 'Optimistic',
        'widgets.pessimistic': 'Pessimistic',
        'widgets.dailyForecastTrend': 'Daily Forecast Trend',
        'widgets.keyFactors': 'Key Factors',
        'widgets.seasonalTrends': 'seasonal trends',
        'widgets.userGrowth': 'user growth',
        'widgets.riskAssessment': 'Risk Assessment',
        'widgets.forecastShowsHighConfidence': 'Forecast shows high confidence with stable growth patterns.',
        'widgets.viewDetails': 'View Details',
        'widgets.setTargets': 'Set Targets',
        'widgets.complianceRadar': 'Compliance Radar',
      
      // Dashboard specific translations
      'dashboard.title': 'Dashboard',
      'dashboard.allUsers': 'All Users',
      'dashboard.b2cCustomers': 'B2C Customers',
      'dashboard.enterpriseClients': 'Enterprise Clients',
      'dashboard.serviceProviders': 'Service Providers',
      'dashboard.completeUserDirectory': 'Complete User Directory',
      'dashboard.user': 'User',
      'dashboard.role': 'Role',
      'dashboard.status': 'Status',
      'dashboard.lastLogin': 'Last Login',
      'dashboard.created': 'Created',
      'dashboard.completed': 'Completed',
      'dashboard.incomplete': 'Incomplete',
      'dashboard.onboardingSteps': 'Onboarding Steps',
      'dashboard.individualCustomersUsing': 'Individual customers using',
      'dashboard.totalCustomers': 'Total customers',
      'dashboard.growthRate': 'Growth rate',
      'dashboard.activeRate': 'Active rate',
      'dashboard.b2bEnterpriseAccounts': 'B2B enterprise accounts',
      'dashboard.thirdPartyServiceProviders': 'Third-party service providers',
      'dashboard.totalServiceProviders': 'Total service providers',
      'dashboard.welcome': 'Welcome to your Clutch Admin dashboard',
      'dashboard.loadingDashboard': 'Loading dashboard...',
      'dashboard.realTime': 'Real-time',
      'dashboard.live': 'Live',
      'dashboard.messages': 'msgs',
      'dashboard.generateReport': 'Generate Report',
      'dashboard.exportData': 'Export Data',
      'dashboard.refresh': 'Refresh',
      'dashboard.realtimeActivityFeed': 'Real-time Activity Feed',
      'dashboard.latestActionsAndEvents': 'Latest actions and system events',
      'dashboard.quickActions': 'Quick Actions',
      'dashboard.commonAdministrativeTasks': 'Common administrative tasks',
      'dashboard.fleetStatus': 'Fleet Status',
      'dashboard.realtimeFleetMonitoring': 'Real-time fleet monitoring',
      'dashboard.noLocation': 'No location',
      'dashboard.performanceMetrics': 'Performance Metrics',
      'dashboard.apiUptimeRequestsErrorsSessions': 'API uptime and requests, errors, and sessions',
      'dashboard.apiUptime': 'API Uptime',
      'dashboard.requestRate': 'Request Rate',
      'dashboard.errorRate': 'Error Rate',
      'dashboard.activeSessions': 'Active Sessions',
      'dashboard.systemAlerts': 'System Alerts',
      'dashboard.criticalNotificationsRequiringAttention': 'Critical notifications requiring attention',
      'dashboard.noAlerts': 'No alerts at this time',
      'dashboard.businessIntelligence': 'Business Intelligence',
      'dashboard.advancedAnalyticsAndPredictiveInsights': 'Advanced analytics and predictive insights for data-driven decisions',
      
      // Widget translations
      'widgets.unifiedOpsPulse': 'Unified Ops Pulse',
      'widgets.realTimeOperationalFunnel': 'Real-time Operational Funnel',
      'widgets.newUsers30d': 'New Users (30d)',
      'widgets.freshSignups': 'Fresh signups',
      'widgets.activeSessions': 'Active Sessions',
      'widgets.currentlyOnline': 'Currently online',
      'widgets.activeVehicles': 'Active Vehicles',
      'widgets.fleetUtilization': 'Fleet utilization',
      'widgets.revenueImpact': 'Revenue Impact',
      'widgets.revenue Impact': 'Revenue Impact',
      'widgets.monthlyRevenue': 'Monthly revenue',
      'widgets.conversionRate': 'Conversion Rate',
      'widgets.efficiency': 'Efficiency',
      'widgets.operationsTrendingPositive': 'Operations trending positive',
      'widgets.churnRiskAnalysis': 'Churn Risk Analysis',
      'widgets.aiPoweredPrediction': 'AI-powered prediction of customer churn risk',
      'widgets.highRisk': 'High Risk',
      'widgets.mediumRisk': 'Medium Risk',
      'widgets.totalAtRisk': 'Total at Risk',
      'widgets.sendRetentionCampaign': 'Send Retention Campaign',
      'widgets.viewAllUsers': 'View All Users',
      'widgets.revenueVsCostMargin': 'Revenue vs Cost Margin',
      'widgets.revenueVsCosts': 'Revenue vs Costs',
      'widgets.monthlyCosts': 'Monthly Costs',
      'widgets.netProfitMargin': 'Net Profit Margin',
      'widgets.costBreakdown': 'Cost Breakdown',
      'widgets.fleetOperations': 'Fleet Operations',
      'widgets.infrastructure': 'Infrastructure',
      'widgets.maintenance': 'Maintenance',
      'widgets.other': 'Other',
      'widgets.aiPoweredForecast': 'AI-Powered Forecast',
      'widgets.nextPeriodRevenueProjection': 'Next Period Revenue Projection',
      'widgets.projectedRevenue': 'Projected Revenue',
      'widgets.baseCase': 'Base Case',
      'widgets.avgConfidence': 'Avg Confidence',
      'widgets.lowRisk': 'Low Risk',
      'widgets.scenarioAnalysis': 'Scenario Analysis',
      'widgets.optimistic': 'Optimistic',
      'widgets.pessimistic': 'Pessimistic',
      'widgets.dailyForecastTrend': 'Daily Forecast Trend',
      'widgets.keyFactors': 'Key Factors',
      'widgets.riskAssessment': 'Risk Assessment',
      'widgets.viewDetails': 'View Details',
      'widgets.setTargets': 'Set Targets',
      'widgets.top5EnterpriseClients': 'Top 5 Enterprise Clients',
      'widgets.byRevenueContribution': 'By revenue contribution & activity level',
      'widgets.totalRevenue': 'Total Revenue',
      'widgets.avgGrowth': 'Avg Growth',
      'widgets.viewAllClients': 'View All Clients',
      'widgets.scheduleReview': 'Schedule Review',
      'widgets.clientInsights': 'Client Insights',
      
      // Status and quality indicators
      'status.excellent': 'Excellent',
      'status.good': 'Good',
      'status.needsAttention': 'Needs Attention',
      'status.poor': 'Poor',
      'status.critical': 'Critical',
      'status.warning': 'Warning',
      'status.info': 'Info',
      'status.success': 'Success',
      'status.error': 'Error',
      
      // Time periods
      'time.days': 'Days',
      'time.hours': 'Hours',
      'time.minutes': 'Minutes',
      'time.seconds': 'Seconds',
      'time.weeks': 'Weeks',
      'time.months': 'Months',
      'time.years': 'Years',
      
      // Common actions
      'actions.view': 'View',
      'actions.edit': 'Edit',
      'actions.delete': 'Delete',
      'actions.create': 'Create',
      'actions.update': 'Update',
      'actions.save': 'Save',
      'actions.cancel': 'Cancel',
      'actions.submit': 'Submit',
      'actions.reset': 'Reset',
      'actions.refresh': 'Refresh',
      'actions.export': 'Export',
      'actions.import': 'Import',
      'actions.download': 'Download',
      'actions.upload': 'Upload',
      'actions.print': 'Print',
      'actions.share': 'Share',
      'actions.copy': 'Copy',
      'actions.paste': 'Paste',
      'actions.cut': 'Cut',
      'actions.undo': 'Undo',
      'actions.redo': 'Redo',
      'common.connecting': 'Connecting',
      'common.offline': 'Offline',
      'common.closing': 'Closing',
      'common.unknown': 'Unknown',
      'common.view': 'View',
      'common.manage': 'Manage',
      
      // CMS Help translations
      'cms.help.title': 'Help Articles CMS',
      'cms.help.description': 'Manage and organize help articles for your users',
      'cms.help.newArticle': 'New Article',
      'cms.help.searchPlaceholder': 'Search articles...',
      'cms.help.allCategories': 'All Categories',
      'cms.help.articles': 'Articles',
      'cms.help.views': 'views',
      'cms.help.updated': 'Updated',
      'cms.help.tabs.articles': 'Articles',
      'cms.help.tabs.categories': 'Categories',
      'cms.help.tabs.analytics': 'Analytics',
      'cms.help.categories.gettingStarted': 'Getting Started',
      'cms.help.categories.fleetManagement': 'Fleet Management',
      'cms.help.categories.billing': 'Billing',
      'cms.help.categories.technicalSupport': 'Technical Support',
      'cms.help.tags.basics': 'Basics',
      'cms.help.tags.tutorial': 'Tutorial',
      'cms.help.tags.fleet': 'Fleet',
      'cms.help.tags.management': 'Management',
      'cms.help.tags.billing': 'Billing',
      'cms.help.tags.payment': 'Payment',
      'cms.help.sampleArticles.gettingStarted.title': 'Getting Started with Clutch',
      'cms.help.sampleArticles.gettingStarted.content': 'Learn the basics of using Clutch for fleet management. This guide covers account setup, navigation, and essential features.',
      'cms.help.sampleArticles.fleetManagement.title': 'Fleet Management Best Practices',
      'cms.help.sampleArticles.fleetManagement.content': 'Discover how to effectively manage your fleet with Clutch. Learn about vehicle tracking, maintenance scheduling, and performance monitoring.',
      'cms.help.sampleArticles.billing.title': 'Understanding Your Billing',
      'cms.help.sampleArticles.billing.content': 'Everything you need to know about billing, payments, and subscription management in Clutch.',
      'cms.help.analytics.totalArticles': 'Total Articles',
      'cms.help.analytics.published': 'Published',
      'cms.help.analytics.totalViews': 'Total Views',
      'cms.help.analytics.categories': 'Categories',
      
      // CRM translations
      'crm.title': 'CRM Dashboard',
      'crm.description': 'Manage customer relationships and interactions',
      'crm.loadingData': 'Loading CRM data...',
      'crm.analytics': 'Analytics',
      'crm.addCustomer': 'Add Customer',
      'crm.totalCustomers': 'Total Customers',
      'crm.activeCustomers': 'Active Customers',
      'crm.openTickets': 'Open Tickets',
      'crm.avgSatisfaction': 'Avg Satisfaction',
      'crm.fromLastMonth': 'from last month',
      'crm.retentionRate': 'retention rate',
      'crm.fromYesterday': 'from yesterday',
      'crm.customerProfiles': 'Customer Profiles',
      'crm.ticketManagement': 'Ticket Management',
      'crm.communicationHistory': 'Communication History',
      'crm.manageCustomerInfo': 'Manage customer information and relationships',
      'crm.searchCustomers': 'Search customers...',
      'crm.filterByStatus': 'Filter by status',
      'crm.allStatus': 'All Status',
      'crm.active': 'Active',
      'crm.prospect': 'Prospect',
      'crm.inactive': 'Inactive',
      'crm.customer': 'Customer',
      'crm.company': 'Company',
      'crm.status': 'Status',
      'crm.totalSpent': 'Total Spent',
      'crm.satisfaction': 'Satisfaction',
      'crm.lastContact': 'Last Contact',
      'crm.viewProfile': 'View Profile',
      'crm.sendMessage': 'Send Message',
      'crm.callCustomer': 'Call Customer',
      'crm.scheduleMeeting': 'Schedule Meeting',
      'crm.viewActivity': 'View Activity',
      'crm.supportTickets': 'Support Tickets',
      'crm.manageCustomerSupport': 'Manage customer support tickets',
      'crm.ticket': 'Ticket',
      'crm.priority': 'Priority',
      'crm.assignedTo': 'Assigned To',
      'crm.created': 'Created',
      'crm.viewDetails': 'View Details',
      'crm.assignToMe': 'Assign to Me',
      'crm.markAsResolved': 'Mark as Resolved',
      'crm.escalate': 'Escalate',
      'crm.timelineOfInteractions': 'Timeline of all customer interactions',
      'crm.phoneCall': 'Phone Call',
      'crm.hoursAgo': 'hours ago',
      'crm.discussedFleetFeatures': 'Discussed fleet management features and pricing options',
      'crm.email': 'Email',
      'crm.dayAgo': 'day ago',
      'crm.sentMonthlyReport': 'Sent monthly usage report and recommendations',
      'crm.meeting': 'Meeting',
      'crm.daysAgo': 'days ago',
      'crm.productDemoCompleted': 'Product demo and onboarding session completed',
      'crm.crmAnalytics': 'CRM Analytics',
      'crm.moveBeyondTickets': 'Move beyond tickets to understand customer health and opportunities',
      
      // Reports translations
      'reports.title': 'Reports',
      'reports.description': 'Generate and manage business reports',
      'reports.loadingReports': 'Loading reports...',
      'reports.reportTemplates': 'Report Templates',
      'reports.createReport': 'Create Report',
      'reports.generateReport': 'Generate Report',
      'reports.totalReports': 'Total Reports',
      'reports.completed': 'Completed',
      'reports.scheduled': 'Scheduled',
      'reports.availableTemplates': 'Available templates',
      'reports.scheduledReports': 'Scheduled Reports',
      'reports.autoGeneratedReports': 'Auto-generated reports',
      'reports.dataProcessed': 'Data Processed',
      'reports.totalRecordsProcessed': 'Total records processed',
      'reports.reports': 'Reports',
      'reports.manageAndViewReports': 'Manage and view all your business reports',
      'reports.reportType': 'Report Type',
      'reports.financial': 'Financial',
      'reports.operational': 'Operational',
      'reports.userAnalytics': 'User Analytics',
      'reports.fleet': 'Fleet',
      'reports.status': 'Status',
      'reports.generating': 'Generating',
      'reports.failed': 'Failed',
      'reports.createdBy': 'Created By',
      'reports.schedule': 'Schedule',
      'reports.records': 'Records',
      'reports.fileSize': 'File Size',
      'reports.createdAt': 'Created At',
      'reports.generatedAt': 'Generated At',
      'reports.nextRun': 'Next Run',
      'reports.downloadReport': 'Download Report',
      'reports.viewReport': 'View Report',
      'reports.createReportDescription': 'Create a new business report with custom parameters',
      'reports.reportName': 'Report Name',
      'reports.enterReportName': 'Enter report name',
      'reports.reportDescription': 'Report Description',
      'reports.startDate': 'Start Date',
      'reports.endDate': 'End Date',
      'reports.once': 'Once',
      'reports.daily': 'Daily',
      'reports.weekly': 'Weekly',
      'reports.monthly': 'Monthly',
      'reports.quarterly': 'Quarterly',
      'reports.useTemplatesDescription': 'Use pre-built templates to quickly create reports',
      'reports.usedTimes': 'Used {count} times',
      'reports.useTemplate': 'Use Template',
      'reports.reportsAnalytics': 'Reports Analytics',
      'reports.automateAndMeasure': 'Automate and measure your reporting efficiency',
      'reports.currentUser': 'Current User',
      'reports.custom': 'Custom',
      
      // Quick Actions translations
      'quickActions.navigatingToUserManagement': 'Navigating to User Management',
      'quickActions.navigatingToFleetManagement': 'Navigating to Fleet Management',
      'quickActions.navigatingToAnalytics': 'Navigating to Analytics',
      'quickActions.navigatingToReports': 'Navigating to Reports',
      'quickActions.navigatingToSettings': 'Navigating to Settings',
      'quickActions.navigatingToCRM': 'Navigating to CRM',
      'quickActions.navigatingToFinance': 'Navigating to Finance',
      'quickActions.generatingReport': 'Generating report...',
      'quickActions.dashboardReport': 'Dashboard Report',
      'quickActions.reportGeneratedSuccessfully': 'Report generated successfully!',
      'quickActions.failedToGenerateReport': 'Failed to generate report',
      'quickActions.exportingData': 'Exporting data...',
      'quickActions.dataExportedSuccessfully': 'Data exported successfully!',
      'quickActions.failedToExportData': 'Failed to export data',
      'quickActions.openingUserCreationForm': 'Opening user creation form',
      'quickActions.openingFleetCreationForm': 'Opening fleet creation form',
      'quickActions.optimizingRoutes': 'Optimizing routes...',
      'quickActions.routesOptimizedSuccessfully': 'Routes optimized successfully!',
      'quickActions.routesOptimized': 'routes optimized',
      'quickActions.failedToOptimizeRoutes': 'Failed to optimize routes',
      'quickActions.refreshingData': 'Refreshing data...',
      'quickActions.dataRefreshedSuccessfully': 'Data refreshed successfully!',
      'quickActions.failedToRefreshData': 'Failed to refresh data',
      'quickActions.sendingNotification': 'Sending notification...',
      'quickActions.notificationSentSuccessfully': 'Notification sent successfully!',
      'quickActions.failedToSendNotification': 'Failed to send notification',
      
      'auth.login': 'Login',
      'auth.logout': 'Logout',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.forgotPassword': 'Forgot Password?',
      'auth.rememberMe': 'Remember Me',
      'auth.signIn': 'Sign In',
      'auth.signUp': 'Sign Up',
      'auth.welcome': 'Welcome',
      'auth.welcomeBack': 'Welcome Back',
      'auth.invalidCredentials': 'Invalid email or password',
      'auth.loginSuccess': 'Login successful',
      'auth.logoutSuccess': 'Logout successful',
      'auth.signingIn': 'Signing in...',
      'auth.errorOccurred': 'An error occurred. Please try again.',
      'language.english': 'English',
      'language.arabic': 'Arabic',
      'header.language': 'Language',
      'header.search': 'Search',
      'header.notifications': 'Notifications',
      'header.myAccount': 'My Account',
      'header.profile': 'Profile',
      'header.settings': 'Settings',
      'sidebar.clutchAdmin': 'Clutch Admin',
      'sidebar.collapse': 'Collapse',
      'sidebar.expand': 'Expand',
      'analytics.title': 'Analytics',
      'analytics.overview': 'Analytics Overview',
      'analytics.description': 'Comprehensive analytics and insights for your platform',
      'analytics.loadingAnalytics': 'Loading analytics...',
      'analytics.failedToLoadAnalytics': 'Failed to load analytics data',
      'analytics.generateReport': 'Generate Report',
      'analytics.exportData': 'Export Data',
      'analytics.refresh': 'Refresh',
      'analytics.searchAnalytics': 'Search analytics...',
      'analytics.filterByTimeRange': 'Filter by time range',
      'analytics.timeRange': 'Time Range',
      'analytics.last7Days': 'Last 7 days',
      'analytics.last30Days': 'Last 30 days',
      'analytics.last90Days': 'Last 90 days',
      'analytics.lastYear': 'Last year',
      'analytics.customRange': 'Custom range',
      'analytics.userAnalytics': 'User Analytics',
      'analytics.revenueAnalytics': 'Revenue Analytics',
      'analytics.fleetAnalytics': 'Fleet Analytics',
      'analytics.engagementAnalytics': 'Engagement Analytics',
      'analytics.reports': 'Reports',
      'analytics.totalUsers': 'Total Users',
      'analytics.activeUsers': 'Active Users',
      'analytics.newUsers': 'New Users',
      'analytics.userGrowth': 'User Growth',
      'analytics.totalRevenue': 'Total Revenue',
      'analytics.monthlyRecurringRevenue': 'Monthly Recurring Revenue',
      'analytics.averageRevenuePerUser': 'Average Revenue Per User',
      'analytics.revenueGrowth': 'Revenue Growth',
      'analytics.totalFleet': 'Total Fleet',
      'analytics.activeFleet': 'Active Fleet',
      'analytics.fleetUtilization': 'Fleet Utilization',
      'analytics.fleetGrowth': 'Fleet Growth',
      'analytics.totalSessions': 'Total Sessions',
      'analytics.averageSessionDuration': 'Average Session Duration',
      'analytics.bounceRate': 'Bounce Rate',
      'analytics.engagementRate': 'Engagement Rate',
      'users.title': 'User Management',
      'users.overview': 'User Overview',
      'users.description': 'Manage users, roles, and permissions',
      'users.loadingUsers': 'Loading users...',
      'users.failedToLoadUsers': 'Failed to load users',
      'users.addUser': 'Add User',
      'users.totalUsers': 'Total Users',
      'users.activeUsers': 'Active Users',
      'users.suspendedUsers': 'Suspended Users',
      'users.searchUsers': 'Search users...',
      'users.filterByStatus': 'Filter by status',
      'users.filterByRole': 'Filter by role',
      'users.allStatuses': 'All Statuses',
      'users.allRoles': 'All Roles',
      'users.active': 'Active',
      'users.suspended': 'Suspended',
      'users.pending': 'Pending',
      'users.platformAdmin': 'Platform Admin',
      'users.enterpriseClient': 'Enterprise Client',
      'users.serviceProvider': 'Service Provider',
      'users.b2cCustomer': 'B2C Customer',
      'users.b2c': 'B2C',
      'users.b2b': 'B2B',
      'users.providers': 'Providers',
      'users.name': 'Name',
      'users.email': 'Email',
      'users.role': 'Role',
      'users.status': 'Status',
      'users.lastLogin': 'Last Login',
      'users.createdAt': 'Created At',
      'users.actions': 'Actions',
      'users.editUser': 'Edit User',
      'users.deleteUser': 'Delete User',
      'users.suspendUser': 'Suspend User',
      'users.activateUser': 'Activate User',
      'users.viewProfile': 'View Profile',
      'users.sendEmail': 'Send Email',
      'users.noUsersFound': 'No users found',
      'users.userGrowth': 'User Growth',
      'users.engagement': 'Engagement',
      'users.onboarding': 'Onboarding',
      'users.roleDistribution': 'Role Distribution',
      'users.churnRisk': 'Churn Risk',
      'widgets.loadingOperationalMetrics': 'Loading operational metrics...',
      'widgets.unableToLoadOperationalMetrics': 'Unable to load operational metrics',
      'widgets.newUsers': 'New Users',
      'widgets.activeUsers': 'Active Users',
      'widgets.fleetVehicles': 'Fleet Vehicles',
      'widgets.operationalPulse': 'Operational Pulse',
      'widgets.overallEfficiency': 'Overall Efficiency',
      'widgets.churnRisk': 'Churn Risk',
      'widgets.critical': 'Critical',
      'widgets.warning': 'Warning',
      'widgets.stable': 'Stable',
      'widgets.margin': 'Margin',
      'widgets.profitability': 'Profitability',
      'widgets.forecast': 'Forecast',
      'widgets.aiPowered': 'AI-Powered',
      'widgets.next7Days': 'Next 7 Days',
      'widgets.next30Days': 'Next 30 Days',
      'widgets.next90Days': 'Next 90 Days',
      'widgets.complianceStatus': 'Compliance Status',
      'widgets.enterpriseClients': 'Enterprise Clients',
      'widgets.topClients': 'Top Clients',
      'widgets.revenueGrowth': 'Revenue Growth',
      'widgets.noData': 'No data available',
      'widgets.refresh': 'Refresh',
      'widgets.fromLastPeriod': 'from last period',
      'widgets.noLocationData': 'No location data',
      'widgets.noAlertsAtThisTime': 'No alerts at this time',
      'widgets.monthlyRevenuePredictions': 'Monthly revenue predictions',
      'widgets.allClear': 'All Clear',
      'widgets.attentionNeeded': 'Attention Needed',
      'widgets.actionRequired': 'Action Required',
      'widgets.high': 'High',
      'widgets.medium': 'Medium',
      'widgets.low': 'Low',
      'widgets.none': 'None',
      'widgets.overdue': 'Overdue',
      'widgets.days': 'days',
      'widgets.excellent': 'Excellent',
      'widgets.good': 'Good',
      'widgets.fair': 'Fair',
      'widgets.poor': 'Poor',
      'widgets.today': 'Today',
      'widgets.yesterday': 'Yesterday',
      'widgets.viewUserDetails': 'View User Details',
      'widgets.sendEmail': 'Send Email',
      'widgets.callUser': 'Call User',
      'widgets.needsAttention': 'Needs Attention',
      'widgets.forecastHighConfidence': 'Forecast shows high confidence with stable growth patterns.',
      'widgets.forecastModerateConfidence': 'Moderate confidence with some variability in projections.',
      'widgets.forecastHighUncertainty': 'High uncertainty - consider additional data sources.',
      'quickActions.refreshAllDashboardData': 'Refresh all dashboard data',
      'quickActions.viewCRM': 'View CRM',
      'quickActions.openCustomerRelationshipManagement': 'Open customer relationship management',
      'quickActions.viewFinance': 'View Finance',
      'quickActions.openFinancialDashboard': 'Open financial dashboard',
      'quickActions.viewSettings': 'View Settings',
      'quickActions.openSystemSettings': 'Open system settings',
      
      // Quick Actions button titles (missing ones)
      'quickActions.addUser': 'Add User',
      'quickActions.createFleet': 'Create Fleet',
      'quickActions.generateReport': 'Generate Report',
      'quickActions.viewAnalytics': 'View Analytics',
      'quickActions.optimizeRoutes': 'Optimize Routes',
      'quickActions.exportData': 'Export Data',
      'quickActions.refreshData': 'Refresh Data',
      
      'widgets.invalidDataStructure': 'Invalid compliance data structure',
      'widgets.complianceStatusSummary': 'Compliance status summary across all areas',
      'widgets.complianceRadar': 'Compliance Radar',
      'widgets.pendingApprovals': 'Pending Approvals',
      'widgets.violations': 'Violations',
      'widgets.securityIncidents': 'Security Incidents',
      'widgets.complianceBreakdown': 'Compliance Breakdown',
      'widgets.awaitingReview': 'Awaiting Review',
      'widgets.complianceViolations': 'Compliance Violations',
      'widgets.policyBreaches': 'Policy Breaches',
      'widgets.securityBreaches': 'Security Breaches',
      'widgets.loading': 'Loading compliance status...',
      'widgets.dataStructureError': 'Data structure error - Check console for details',
      'widgets.dataFormatMismatch': 'The compliance data received does not match the expected format.',
      'widgets.unableToLoad': 'Unable to load compliance status',
      'widgets.auditTimeline': 'Audit Timeline',
      'widgets.lastAudit': 'Last Audit',
      'widgets.completedSuccessfully': 'Completed successfully',
      'widgets.passed': 'Passed',
      'widgets.nextAudit': 'Next Audit',
      'widgets.scheduledAudit': 'Scheduled audit',
      'widgets.complianceProgress': 'Compliance Progress',
      'widgets.overallCompliance': 'Overall Compliance',
      'widgets.exportReport': 'Export Report',
      'widgets.complianceInsights': 'Compliance Insights',
      'widgets.allRequirementsMet': 'All compliance requirements are met',
      'widgets.attentionNeededAreas': 'Some areas need attention - review pending approvals',
      'widgets.immediateActionRequired': 'Immediate action required - address violations and incidents',
      'widgets.nextAuditIn': 'Next audit in {days} days',
      'widgets.approvalsPendingReview': '{count} approvals pending review',
      'widgets.violationsNeedResolution': '{count} compliance violations need resolution',
      
      // Enterprise translations
      'enterprise.revenueDistribution': 'Revenue Distribution',
      'enterprise.growthAnalysis': 'Growth Analysis',
      'enterprise.growingClients': 'Growing Clients',
      'enterprise.decliningClients': 'Declining Clients',
      'enterprise.viewAllClients': 'View All Clients',
      'enterprise.scheduleReview': 'Schedule Review',
      'enterprise.clientInsights': 'Client Insights',
      'enterprise.topClientContributes': 'Top client contributes {percentage}% of total revenue',
      'enterprise.clientsShowingGrowth': '{count} out of {total} clients showing positive growth',
      'enterprise.averageClientActivity': 'Average client activity level: {percentage}%',
      'enterprise.totalEnterpriseRevenue': 'Total enterprise revenue: {amount}',
      
      // Notifications translations
      'notifications.noNotifications': 'No notifications at this time',
  
  // Navigation translations
  'navigation.dashboard': 'Dashboard',
  'navigation.usermanagement': 'User Management',
  'navigation.fleetmanagement': 'Fleet Management',
  'navigation.crm': 'CRM',
  'navigation.chat&messaging': 'Chat & Messaging',
  'navigation.ai&mldashboard': 'AI & ML Dashboard',
  'navigation.enterpriseb2b': 'Enterprise B2B',
  'navigation.finance': 'Finance',
  'navigation.legal': 'Legal',
  'navigation.hr': 'HR',
  'navigation.featureflags': 'Feature Flags',
  'navigation.communication': 'Communication',
  'navigation.analytics': 'Analytics',
  'navigation.mobileapps': 'Mobile Apps',
  'navigation.cms': 'CMS',
  'navigation.marketing': 'Marketing',
  'navigation.projectmanagement': 'Project Management',
  'navigation.settings': 'Settings',
  'navigation.reporting': 'Reporting',
  'navigation.integrations': 'Integrations',
  'navigation.audittrail': 'Audit Trail',
  'navigation.apidocumentation': 'API Documentation',
  'navigation.assetmanagement': 'Asset Management',
  'navigation.vendormanagement': 'Vendor Management',
  'navigation.systemhealth': 'System Health',
      
      // Assets translations
      'assets.title': 'Asset Management',
      'assets.description': 'Track and manage your organization\'s assets',
      'assets.loadingAssets': 'Loading assets...',
      'assets.totalAssets': 'Total Assets',
      'assets.totalValue': 'Total Value',
      'assets.maintenanceDue': 'Maintenance Due',
      'assets.assignedAssets': 'Assigned Assets',
      'assets.active': 'active',
      'assets.inactive': 'inactive',
      'assets.currentMarketValue': 'Current market value',
      'assets.next30Days': 'Next 30 days',
      'assets.currentlyAssigned': 'Currently assigned',
      'assets.assets': 'Assets',
      'assets.manageAndTrack': 'Manage and track your organization\'s assets',
      'assets.searchAssets': 'Search assets...',
      'assets.type': 'Type',
      'assets.allTypes': 'All Types',
      'assets.vehicle': 'Vehicle',
      'assets.itHardware': 'IT Hardware',
      'assets.equipment': 'Equipment',
      'assets.furniture': 'Furniture',
      'assets.status': 'Status',
      'assets.allStatus': 'All Status',
      'assets.maintenance': 'Maintenance',
      'assets.retired': 'Retired',
      'assets.currentValue': 'Current Value',
      'assets.location': 'Location',
      'assets.assignedTo': 'Assigned To',
      'assets.unassigned': 'Unassigned',
      'assets.nextService': 'Next Service',
      'assets.purchased': 'Purchased',
      'assets.serial': 'Serial',
      'assets.scheduleMaintenance': 'Schedule Maintenance',
      'assets.assignAsset': 'Assign Asset',
      'assets.addAsset': 'Add Asset',
      'assets.recentMaintenance': 'Recent Maintenance',
      'assets.latestMaintenanceActivities': 'Latest maintenance activities and upcoming services',
      'assets.by': 'By',
      'assets.addNewAsset': 'Add New Asset',
      'assets.registerNewAsset': 'Register a new asset in the system.',
      'assets.assetName': 'Asset Name',
      'assets.category': 'Category',
      'assets.filterByType': 'Filter by type...',
      'assets.assetDescription': 'Asset description',
      'assets.serialNumber': 'Serial Number',
      'assets.model': 'Model',
      'assets.manufacturer': 'Manufacturer',
      'assets.purchaseDate': 'Purchase Date',
      'assets.purchasePrice': 'Purchase Price (EGP)',
      'assets.currentValueEGP': 'Current Value (EGP)',
      'assets.building': 'Building',
      'assets.buildingName': 'Building name',
      'assets.floor': 'Floor',
      'assets.room': 'Room',
      'assets.roomNumber': 'Room number',
      'assets.cancel': 'Cancel',
      'assets.scheduleMaintenanceTitle': 'Schedule Maintenance',
      'assets.scheduleMaintenanceForAsset': 'Schedule maintenance for an asset.',
      'assets.selectAsset': 'Select asset',
      'assets.maintenanceType': 'Maintenance Type',
      'assets.routine': 'Routine',
      'assets.repair': 'Repair',
      'assets.inspection': 'Inspection',
      'assets.upgrade': 'Upgrade',
      'assets.maintenanceDescription': 'Description',
      'assets.describeMaintenanceWork': 'Describe the maintenance work',
      'assets.date': 'Date',
      'assets.estimatedCost': 'Estimated Cost (EGP)',
      'assets.notes': 'Notes',
      'assets.additionalNotes': 'Additional notes',
      'assets.assignAssetTitle': 'Assign Asset',
      'assets.assignAssetToEmployee': 'Assign an asset to an employee.',
      'assets.assignTo': 'Assign To',
      'assets.selectEmployee': 'Select employee',
      'assets.assignmentDate': 'Assignment Date',
      'assets.assignmentNotes': 'Assignment notes',
      'assets.viewDetails': 'View Details',
      'assets.editAsset': 'Edit Asset',
      'assets.maintenanceHistory': 'Maintenance History',
      'assets.viewAnalytics': 'View Analytics',
      'assets.manageAssignment': 'Manage Assignment',
      'assets.deleteAsset': 'Delete Asset',
      
      // Sales translations
      'sales.title': 'Sales Management',
      'sales.subtitle': 'Manage leads, deals, contracts, and sales performance',
      'sales.export': 'Export',
      'sales.newLead': 'New Lead',
      'sales.newDeal': 'New Deal',
      'sales.newContract': 'New Contract',
      'sales.newPartner': 'New Partner',
      'sales.totalLeads': 'Total Leads',
      'sales.qualifiedLeads': 'Qualified Leads',
      'sales.totalDeals': 'Total Deals',
      'sales.totalValue': 'Total Value',
      'sales.overview': 'Overview',
      'sales.leads': 'Leads',
      'sales.deals': 'Deals',
      'sales.contracts': 'Contracts',
      'sales.partners': 'Partners',
      'sales.searchLeads': 'Search leads...',
      'sales.status': 'Status',
      'sales.type': 'Type',
      'sales.allStatuses': 'All Statuses',
      'sales.allTypes': 'All Types',
      'sales.new': 'New',
      'sales.contacted': 'Contacted',
      'sales.qualified': 'Qualified',
      'sales.converted': 'Converted',
      'sales.lost': 'Lost',
      'sales.shop': 'Shop',
      'sales.importer': 'Importer',
      'sales.manufacturer': 'Manufacturer',
      'sales.fleet': 'Fleet',
      'sales.insurance': 'Insurance',
      'sales.company': 'Company',
      'sales.contact': 'Contact',
      'sales.assignedTo': 'Assigned To',
      'sales.value': 'Value',
      'sales.created': 'Created',
      'sales.actions': 'Actions',
      'sales.view': 'View',
      'sales.call': 'Call',
      'sales.email': 'Email',
      'sales.deal': 'Deal',
      'sales.pipeline': 'Pipeline',
      'sales.stage': 'Stage',
      'sales.probability': 'Probability',
      'sales.createContract': 'Create Contract',
      'sales.contract': 'Contract',
      'sales.lead': 'Lead',
      'sales.template': 'Template',
      'sales.download': 'Download',
      'sales.partnersComingSoon': 'Partners management coming soon',
      'sales.salesPipeline': 'Sales Pipeline',
      'sales.pipelineValue': 'Pipeline Value',
      'sales.ofDeals': 'of Deals',
      'sales.ofValue': 'of Value',
      'sales.conversionRate': 'Conversion Rate',
      'sales.conversionRateDescription': 'Percentage of leads that convert to deals',
      'sales.leadConversion': 'Lead Conversion',
      'sales.overallConversionRate': 'Overall Conversion Rate',
      'sales.outOf': 'out of',
      'sales.leadsConverted': 'leads converted',
      'sales.conversionFunnel': 'Conversion Funnel',
      'sales.avgDays': 'avg days',
      'sales.conversion': 'conversion',
      'sales.keyInsights': 'Key Insights',
      'sales.highestDropOff': 'Highest Drop-off',
      'sales.highestDropOffDescription': 'Most leads are lost during qualification stage',
      'sales.avgConversionTime': 'Average Conversion Time',
      'sales.avgConversionTimeDescription': 'Leads take 14.5 days on average to convert',
      'sales.revenueForecast': 'Revenue Forecast',
      'sales.forecast': 'Forecast',
      'sales.target': 'Target',
      'sales.vsPreviousQuarter': 'vs Previous Quarter',
      'sales.quarterlyPerformance': 'Quarterly Performance',
      'sales.actual': 'Actual',
      'sales.forecasted': 'Forecasted',
      'sales.forecastAccuracy': 'Forecast Accuracy',
      'sales.yearlyGrowth': 'Yearly Growth',
      'sales.teamPerformance': 'Team Performance',
      'sales.quotaAchievement': 'Quota Achievement',
      'sales.totalRevenue': 'Total Revenue',
      'sales.individualPerformance': 'Individual Performance',
      'sales.revenue': 'Revenue',
      'sales.quotaProgress': 'Quota Progress',
      'sales.teamInsights': 'Team Insights',
      'sales.topPerformer': 'Top Performer',
      'sales.exceedingQuota': 'is exceeding quota targets',
      'sales.teamAverage': 'Team Average',
      'sales.teamAverageDescription': 'Team is performing above industry standards',
      'sales.improvementArea': 'Improvement Area',
      'sales.improvementAreaDescription': 'Focus on lead qualification process',
      'sales.excellent': 'Excellent',
      'sales.good': 'Good',
      'sales.average': 'Average',
      'sales.needs_improvement': 'Needs Improvement',
      'sales.contractStatus': 'Contract Status',
      'sales.pendingLegal': 'Pending Legal',
      'sales.approved': 'Approved',
      'sales.recentContracts': 'Recent Contracts',
      'sales.noContracts': 'No contracts found',
      'sales.statusBreakdown': 'Status Breakdown',
      'sales.draft': 'Draft',
      'sales.printed': 'Printed',
      'sales.signed_uploaded': 'Signed & Uploaded',
      'sales.pending_legal': 'Pending Legal',
      'sales.rejected': 'Rejected',
      'sales.retry': 'Retry',
      'sales.errorFetchingContracts': 'Error fetching contracts',
      'sales.communicationHistory': 'Communication History',
      'sales.totalCommunications': 'Total Communications',
      'sales.successRate': 'Success Rate',
      'sales.recentCommunications': 'Recent Communications',
      'sales.noCommunications': 'No communications found',
      'sales.communicationBreakdown': 'Communication Breakdown',
      'sales.byType': 'By Type',
      'sales.byOutcome': 'By Outcome',
      'sales.visit': 'Visit',
      'sales.whatsapp': 'WhatsApp',
      'sales.left-msg': 'Left Message',
      'sales.no-answer': 'No Answer',
      'sales.successful': 'Successful',
      'sales.errorFetchingCommunications': 'Error fetching communications',
      'sales.prospect': 'Prospect',
      'sales.proposal': 'Proposal',
      'sales.negotiation': 'Negotiation',
      'sales.signed': 'Signed',
      'sales.errorFetchingPipeline': 'Error fetching pipeline data',
      'sales.errorFetchingLeads': 'Error fetching leads',
      'sales.errorFetchingDeals': 'Error fetching deals',
      'sales.errorFetchingPartners': 'Error fetching partners',
      'sales.errorFetchingActivities': 'Error fetching activities',
      'sales.errorFetchingTeamPerformance': 'Error fetching team performance'
    };


    // Try to get translation from loaded translations first, then fallback
    const foundTranslation = getNestedValue(translations, key);
    let translation = foundTranslation || fallbackTranslations[key] || key;
    
    
    // Ensure we always return a string
    if (typeof translation !== 'string') {
      console.warn(`Translation for key "${key}" is not a string:`, translation);
      translation = key; // Fallback to the key itself
    }
    
    if (params && typeof params === 'object') {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(`{${paramKey}}`, params[paramKey]);
      });
    }
    
    return translation;
    } catch (error) {
      console.error(`Translation error for key "${key}":`, error);
      return key; // Fallback to the key itself if there's any error
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
